on: pull_request
name: CI
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11 Pro']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Testing
        run: |
          cd ProjectName
          xcodebuild clean test -project GHFollowers.xcodeproj -scheme GHFollowers -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
           destination: ${{ matrix.destination }}
           CODECOV_TOKEN: ${{ secrets.codecov_token }}
